// dapps/appkit/vue-multichain/src/App.vue

<template>
   <div class="pages">
      <img src="/reown.svg" alt="Reown" width="150" height="150" />
      <h1>AppKit multichain vue Example</h1>

      <appkit-button />
      <ActionButtonList />
      <InfoList />
    </div>
</template>


<script>
import {
  createAppKit,
} from '@reown/appkit/vue'
import { solanaWeb3JsAdapter, wagmiAdapter, networks, projectId } from './config/index'

import ActionButtonList from "./components/ActionButton.vue"; 
import InfoList from "./components/InfoList.vue";

// Initialize AppKit
createAppKit({
  adapters: [wagmiAdapter, solanaWeb3JsAdapter],
  networks,
  projectId,
  metadata: {
    name: 'AppKit Vue Example',
    description: 'AppKit Vue Example',
    url: 'https://reown.com/appkit',
    icons: ['https://avatars.githubusercontent.com/u/179229932?s=200&v=4']
  }
})

export default {
  name: "App",
  components: {
    ActionButtonList,
    InfoList
  },
};
</script>

// dapps/appkit/react-solana/src/App.tsx
import { createAppKit } from '@reown/appkit/react'
import { solana, solanaTestnet, solanaDevnet } from '@reown/appkit/networks'
import { metadata, projectId, solanaWeb3JsAdapter } from './config'
import { ActionButtonList } from './components/ActionButtonList'
import { InfoList } from './components/InfoList'

import "./App.css"

// Create modal
createAppKit({
  projectId,
  metadata,
  networks: [solana, solanaTestnet, solanaDevnet],
  adapters: [solanaWeb3JsAdapter],
})

export function App() {


  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
      <img src="/reown.svg" alt="Reown" style={{ width: '150px', height: '150px' }} />
      <h2>Reown AppKit + Solana</h2>
      <appkit-button />
      <ActionButtonList />
      <InfoList />
    </div>
  )
}

export default App
