// dapps/vue-dapp-auth/components/QrView.vue
<template>
  <div class="tw-card tw-text-center tw-space-y-8 tw-w-full tw-max-w-sm">
    <qr-code
      background="transparent"
      :foreground="foreground"
      class="qr-code tw-py-4"
      :value="uri"
      :size="400"
    />

    <hr class="tw-mx-12">

    <div class="tw-space-y-4 tw-flex tw-flex-col tw-items-center">
      <div class="tw-text-center">
        <h3 class="tw-text-dim-1">
          Scan with your phone
        </h3>
        <p class="tw-text-dim-2">
          Open your camera app or mobile wallet and scan the code to connect
        </p>
      </div>

      <button class="tw-button-secondary tw-text-lg tw-w-full sm:tw-min-w-[7em]" @click="copyLink()">
        <icon name="copy" />
        {{ message }}
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import QrCode from 'qrcode.vue'

const props = defineProps<{
  uri: string
}>()

const colorMode = useColorMode()
const foreground = computed(
  () => colorMode.value === Theme.dark
    ? '#fff'
    : '#000',
)

const message = refAutoReset('Copy to clipboard', 1000)

const copyLink = async () => {
  await navigator.clipboard.writeText(props.uri)
  message.value = 'Copied!'
}
</script>

<style scoped>
  .qr-code {
    @apply tw-mx-auto;
    width: 100% !important;
    height: auto !important;
    max-width: theme('maxWidth.xs');
  }
</style>

// dapps/react-dapp-auth/views/QrView.tsx
import {
  Text,
  Container,
  Divider,
  Flex,
  Heading,
  useToast,
  Button,
  Grid,
} from "@chakra-ui/react";
import Qrcode from "qrcode";
import { useEffect, useRef } from "react";

const QrView: React.FC<{ uri: string }> = ({ uri }) => {
  const canvasRef = useRef(null);
  const toast = useToast();

  useEffect(() => {
    if (uri && canvasRef.current) Qrcode.toCanvas(canvasRef.current, uri);
  }, [uri, canvasRef]);

  const onClick = async () => {
    await navigator.clipboard.writeText(uri);
    toast({
      title: "Copied URI",
    });
  };

  return (
    <Container>
      <Flex
        className="bg-secondary"
        alignItems="center"
        borderRadius="24px"
        flexDir="column"
      >
        <Grid
          padding="2em"
          borderTopRadius="24px"
          placeItems="center"
          className="bg-qr"
          borderBottom="solid 1px white"
          width="100%"
          height="100%"
        >
          <canvas
            onClick={onClick}
            ref={canvasRef}
            height="20em"
            width="20em"
            style={{
              borderRadius: "24px",
              minWidth: "25em",
              minHeight: "25em",
            }}
          />
        </Grid>

        <Flex gap="3" flexDir="column" alignItems="center" padding="2em">
          <Text fontWeight={800} textAlign="center" fontSize="1.5em">
            Scan with your phone
          </Text>

          <Text fontWeight={600} textAlign="center">
            Open your camera app or mobile wallet and scan the code to connect
          </Text>
          <Button onClick={onClick} borderRadius="16px" className="wc-button">
            Copy to clipboard
          </Button>
        </Flex>
      </Flex>
    </Container>
  );
};

export default QrView;
